sudo: required
services:
  - docker

before_install:
  - docker build -t icoder/docker-react -f Dockerfile.dev .

script:
  # - docker run icoder/docker-react npm run test -- --coverage
  - docker run -e CI=true icoder/docker-react npm run test